# Generated by Django 5.0.3 on 2025-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subtag', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('video', models.URLField(blank=True)),
                ('content_images', models.JSONField(blank=True, default=list)),
                ('blogcontentvideo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
