# Generated by Django 5.0.3 on 2025-06-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosioloji', '0001_initial'),
    ]

    operations = [
    ]
