# Generated by Django 5.2.3 on 2025-06-22 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosioloji', '0002_blogpost_video_alter_blogpost_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=datetime.datetime(2025, 6, 22, 14, 37, 23, 317615, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contentImages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2025, 6, 22, 14, 37, 31, 988811, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default=datetime.datetime(2025, 6, 22, 14, 37, 40, 130765, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
