# Generated by Django 5.0.3 on 2025-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosioloji', '0002_auto_20250624_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
