# Generated by Django 5.0.3 on 2025-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosioloji', '0003_post_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='callout',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='product_card',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
